// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "gokit/datastore/datastorecrud/user/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeCreateHandler(m, endpoints, options["Create"])
	makeGetHandler(m, endpoints, options["Get"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	makeUpdateHandler(m, endpoints, options["Update"])
	makeAllHandler(m, endpoints, options["All"])
	return m
}
